# Generated by Django 5.1.1 on 2024-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('loan_representative', 'loan_representative'), ('loan_sanctioning_officer', 'loan_sanctioning_officer'), ('admin', 'admin'), ('account_head', 'account_head')], max_length=24, null=True),
        ),
    ]
