# Generated by Django 5.1.1 on 2024-09-06 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_principal_amount', models.FloatField(blank=True, default=0)),
                ('interest_rate', models.FloatField(blank=True, default=0)),
                ('total_amount_and_processing_fees', models.FloatField(blank=True, default=0)),
                ('installment', models.IntegerField(blank=True, default=0)),
                ('maturity_date', models.DateField(blank=True, default='2000-12-12')),
                ('sanction_letter', models.FileField(blank=True, default=0, upload_to='customer/loan/')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('pending', 'pending'), ('done', 'done'), ('rejected', 'rejected')], default=0, max_length=250)),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, default=0, max_length=250)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Loans', to='application_generation.application')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Signature')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_transactions', to='loan_sanctioning.loan')),
                ('transaction_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=250)),
                ('vendor_type', models.CharField(blank=True, default=0, max_length=250)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('address', models.TextField(blank=True, default=0, max_length=25)),
                ('city', models.CharField(blank=True, default=0, max_length=250)),
                ('state', models.CharField(blank=True, default=0, max_length=250)),
                ('country', models.CharField(blank=True, default=0, max_length=250)),
                ('pin_code', models.IntegerField(blank=True, default=0)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('bank_name', models.CharField(blank=True, default=0, max_length=250)),
                ('passbook_copy', models.FileField(blank=True, default=0, upload_to='customer/vendor/')),
                ('current_account_no', models.CharField(blank=True, default=0, max_length=25)),
                ('ifsc_code', models.CharField(blank=True, default=0, max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendors', to='application_generation.application')),
            ],
        ),
    ]
