# Generated by Django 5.1.1 on 2024-09-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
