# Generated by Django 5.1.1 on 2024-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('ok', 'ok'), ('late', 'late'), ('', '')], default='pending', max_length=100),
        ),
    ]
