# Generated by Django 5.1.1 on 2024-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_alter_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('late', 'late'), ('ok', 'ok'), ('', '')], default='pending', max_length=100),
        ),
    ]
